on:
  push:
    branches: [ "main" , "master" ]

  workflow_dispatch:
  
jobs:
  commit-hash:
    name: Commit SHA
    runs-on: ubuntu-latest
    outputs:
      sha7: ${{ steps.commit-hash.outputs.sha7 }}
    steps:
      - name: Get Commit SHA
        id: commit-hash
        run: echo "sha7=$(echo ${GITHUB_SHA} | cut -c1-7)" >> "$GITHUB_OUTPUT"

  docker:
    uses: GBADsInformatics/DevopsWorkflows/.github/workflows/docker.yml@v2.0
    secrets: inherit
    with:
      IMAGE_NAME: data-stories-dash

  aws:
    needs: [commit-hash, docker]
    uses: GBADsInformatics/DevopsWorkflows/.github/workflows/aws.yml@v2.0
    secrets:
      template-input: >-
        ApplicationName=datastories-dash,
        DockerURI=gbadsinformatics/data-stories-dash:${{ needs.commit-hash.outputs.sha7 }},
        BaseURL=/dashboards/datastories,
        ListenerRulePriority=11,
        MajorInfo1=${{ secrets.MAJOR_INFO1 }},
        MajorInfo2=${{ secrets.MAJOR_INFO2 }},
        MajorKey=${{ secrets.MAJOR_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    with:
      stack-name: datastories-dash-stack
      stack-update-timeout: 8
